_demo_secured:
    resource: "@AcmeDemoBundle/Controller/SecuredController.php"
    type:     annotation

_demo:
    resource: "@AcmeDemoBundle/Controller/DemoController.php"
    type:     annotation
    prefix:   /dm
 
    
_testWelcome:    
    resource: "@AcmeDemoBundle/Controller/WelcomeController.php"
    type:     annotation
    prefix:   /wel
    
BloggerBlogBundle:
    resource: "@BloggerBlogBundle/Resources/config/routing.yml"
    prefix:   /